DtdcCashCounter/Controllers/BookingController.cs
using DtdcCashCounter.EntityFr;
using DtdcCashCounter.Models;
using Microsoft.Reporting.WebForms;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Net.NetworkInformation;
using System.Web;
using System.Web.Mvc;
using ZXing;

namespace DtdcCashCounter.Controllers
{
    public class BookingController : Controller
    {
        db_a91f79_zionenterprisesEntities db = new db_a91f79_zionenterprisesEntities();

        Add_History add_History = new Add_History();
        // GET: Booking
        [SessionTimeout]
        public ActionResult Printreceipt()
        {
            return View();
        }

        [SessionTimeout]
        [HttpPost]
        public ActionResult Printreceipt(Receipt_details reciept_Details, string Submit, bool? DisableDisc)
        {

            var consignmentno = reciept_Details.Consignment_No;



            ////credit Amount logic///

            reciept_Details.Paid_Amount =  Convert.ToInt16(reciept_Details.Credit_Amount);
           
            /////////////////////////


            ViewBag.Insuarance = reciept_Details.Shipmenttype;
            ViewBag.yesinsurance = reciept_Details.Insurance;

            var consignment = db.Receipt_details.Where(m => m.Consignment_No == reciept_Details.Consignment_No).FirstOrDefault();

            if (consignment != null)
            {
                ModelState.AddModelError("Consignment", "Consignment Allready Exist");
            }






            string savePath = "";

            if (ModelState.IsValid)
            {

                reciept_Details.Pf_Code = Session["pfCode"].ToString();
                reciept_Details.User_Id = Convert.ToInt64(Session["EmpId"]);


                /////////////////////gettting current time


                DateTime serverTime = DateTime.Now; // gives you current Time in server timeZone
                DateTime utcTime = serverTime.ToUniversalTime(); // convert it to Utc using timezone setting of server computer

                TimeZoneInfo tzi = TimeZoneInfo.FindSystemTimeZoneById("India Standard Time");
                DateTime localTime = TimeZoneInfo.ConvertTimeFromUtc(utcTime, tzi);

                reciept_Details.Datetime_Cons = localTime;

                //////////////////////////////////////////////////////////////////////////

                
                db.Receipt_details.Add(reciept_Details);
                db.SaveChanges();

                if (Submit == "Sms")
                {

                    callapi(reciept_Details.sender_phone, reciept_Details.Consignment_No, reciept_Details.Charges_Total, reciept_Details.Destination);
                }



                if (Submit == "Print")
                {
                    ////////////////test////////////////////
                    var getFileName = PrintMethod(reciept_Details.Consignment_No);

                    string baseUrl = Request.Url.Scheme + "://" + Request.Url.Authority +
    Request.ApplicationPath.TrimEnd('/') + "/";

                     savePath = baseUrl + "/ConsignmentPDF/Recieptdetails-" + reciept_Details.Consignment_No.Replace("/", "-") + ".pdf";

                    // return Redirect(savePath);
                    ViewBag.ImagePath = savePath;
                    //return Redirect(savePath);
                    ////////////////test////////////////////
                }
                /////////////////Setting Next  Consignment number

                //char ch = reciept_Details.Consignment_No[1];

                //string ch = reciept_Details.Consignment_No;

                String value = reciept_Details.Consignment_No;
                int startIndex = 0;
                int endindex = 2;
                int length = value.Length;

                String substring = value.Substring(startIndex, endindex);

                string strno = value.Remove(startIndex, endindex);

                
                //long consignnumber = Convert.ToInt64(reciept_Details.Consignment_No.Substring(1));
                int consignnumber =Convert.ToInt32(strno);

                consignnumber = consignnumber + 1;

                // ViewBag.nextconsignment = ch + "" + consignnumber;

                ViewBag.nextconsignment = substring + "" + consignnumber;

                //ViewBag.nextconsignment = consignnumber;

                ///// Adding Wallet Points To Phone Number///
                //WalletPoint AddPoints = db.WalletPoints.Where(m => m.MobileNo == reciept_Details.sender_phone).FirstOrDefault();


                ////////************** subtracting Discount //////////////////////



                /////////////////////////////////////////

                //if (AddPoints == null)
                //{
                //    float? points = 0;

                //    WalletPoint wp = new WalletPoint();

                //    wp.MobileNo = reciept_Details.sender_phone;

                //    if (DisableDisc != true)
                //    {
                //        if (reciept_Details.Consignment_No.ToUpper().StartsWith("N"))
                //        {
                //            points = (float)(0.025) * reciept_Details.Charges_Total;
                //        }
                //        else
                //        {
                //            points = (float)(0.05) * reciept_Details.Charges_Total;
                //        }
                //    }
                //    else
                //    {
                //        points = 0;
                //    }
                //    wp.Wallet_Money = points;

                //    wp.Datetime_Wa = GetLocalTime.GetDateTime();

                //    db.WalletPoints.Add(wp);
                //    add_History.addHistory("Added", reciept_Details.Pf_Code, reciept_Details.User_Id, wp.Wallet_Money, reciept_Details.Consignment_No, reciept_Details.sender_phone);
                //    MemberShip(reciept_Details.sender_phone);

                //}
                //else
                //{
                //    AddPoints.Wallet_Money = AddPoints.Wallet_Money - reciept_Details.Discount;

                //    float? points = 0;

                //    if (reciept_Details.Discount > 0)
                //    {
                //        add_History.addHistory("Redeemed", reciept_Details.Pf_Code, reciept_Details.User_Id, reciept_Details.Discount, reciept_Details.Consignment_No, reciept_Details.sender_phone);
                //    }

                //    if (DisableDisc != true)
                //    {
                //        if (reciept_Details.Consignment_No.ToUpper().StartsWith("N"))
                //        {

                //            var add = (float)(0.025) * reciept_Details.Charges_Total;

                //            AddPoints.Wallet_Money = (float)AddPoints.Wallet_Money + add;

                //            PointsAdded(reciept_Details.sender_phone, add, AddPoints.Wallet_Money);

                //            add_History.addHistory("Added", reciept_Details.Pf_Code, reciept_Details.User_Id, add, reciept_Details.Consignment_No, reciept_Details.sender_phone);

                //        }
                //        else
                //        {
                //            var add = (float)(0.05) * reciept_Details.Charges_Total;

                //            AddPoints.Wallet_Money = (float)AddPoints.Wallet_Money + add;

                //            PointsAdded(reciept_Details.sender_phone, add, AddPoints.Wallet_Money);

                //            add_History.addHistory("Added", reciept_Details.Pf_Code, reciept_Details.User_Id, add, reciept_Details.Consignment_No, reciept_Details.sender_phone);
                //        }
                //    }



                //    db.Entry(AddPoints).State = EntityState.Modified;

                //}
                //db.SaveChanges();

                //////////Alert After Added Cosingmnt///
                ViewBag.Success = "Consignment Added Successfully...!!!";
                //////////////////////////////////////
                if (Submit == "Print")
                {

                    ViewBag.pdf = false;
                    ViewBag.pdf = true;
                    ViewBag.Consignmetno = reciept_Details.Consignment_No;
                }


                ModelState.Clear();


                //return View(new Receipt_details());
                //return View(Printcashcounter(consignmentno));
               
            }

            //ViewBag.WalletPopints = reciept_Details.Discount;
            ViewBag.Discount = reciept_Details.Discount;

           
          
            //return View();
            return View(reciept_Details);

        }

        public string RecallPrintMethod(string consignmentno)
        {

            string imageName = consignmentno + "." + ImageType.Png;
            string imagePath = "/BarcodeImages/" + imageName;

            string baseUrl = Request.Url.Scheme + "://" + Request.Url.Authority +
                     Request.ApplicationPath.TrimEnd('/');



            string imageServerPath = Server.MapPath("~" + imagePath);


            // Usage 
            string data = consignmentno; // Your barcode data
            Image barcodeImage = GenerateBarcode(data);


            barcodeImage.Save(imageServerPath, System.Drawing.Imaging.ImageFormat.Png);

            // Dispose of the image
            barcodeImage.Dispose();

            var getRecipt = db.Receipt_details.Where(x => x.Consignment_No == consignmentno).FirstOrDefault();
            getRecipt.BarcodeImage = baseUrl + imagePath;
            db.SaveChanges();



            return Printcashcounter(consignmentno);

        }
        public ActionResult PrintMethod(string consignmentno)
        {
            ////////////////test print reciept////////////////////

DtdcCashCounter/Controllers/WalletController.cs
using DtdcCashCounter.EntityFr;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DtdcCashCounter.Controllers
{
    public class WalletController : Controller
    {
        db_a91f79_zionenterprisesEntities db = new db_a91f79_zionenterprisesEntities();
        // GET: Wallet
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult WalletHistory(string phone)
        {
            List<wallet_History> wallet_History = db.wallet_History.Where(m => m.mobile_no == phone).ToList();
            return View(wallet_History);
        }


    }
}

DtdcCashCounter/Views/Reports/Chart.cshtml
@{
    ViewBag.Title = "Chart";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}


<link href="~/admin-lte/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css" rel="stylesheet" />
<script src="~/admin-lte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>


<div class="content-wrapper">
    @using (Html.BeginForm())
    {
        <div class="col-sm-12">
            <div class="col-md-3">
                <div class="form-group">
                    <label>To Date:</label>
                    <div class="input-group date">
                        <div class="input-group-addon">
                            <i class="fa fa-calendar"></i>
                        </div>
                        @if (ViewBag.Fromdatetime != null)
                        {
                            <input name="Fromdatetime" class="form-control pull-right" value="@ViewBag.Fromdatetime" id="datepicker" type="text">
                        }
                        else
                        {
                            <input name="Fromdatetime" class="form-control pull-right" id="datepicker" type="text">
                        }
                        @Html.ValidationMessage("Fromdateeror")
                    </div>
                </div>
            </div>

            <div class="col-md-3">
                <div class="form-group">
                    <label>To Date:</label>
                    <div class="input-group date">
                        <div class="input-group-addon">
                            <i class="fa fa-calendar"></i>
                        </div>
                        @if (ViewBag.ToDatetime != null)
                        {
                            <input name="ToDatetime" class="form-control pull-right" value="@ViewBag.ToDatetime" id="datepicker1" type="text">
                        }
                        else
                        {
                            <input name="ToDatetime" class="form-control pull-right" id="datepicker1" type="text">
                        }
                        @Html.ValidationMessage("Todateeror")
                    </div>

                </div>
            </div>

            <div class="col-md-3" style="margin-top:25px">
                <div class="form-group">
                    <button type="submit" class="btn btn-block btn-success">Search</button>
                </div>
            </div>
        </div>
    }
        <div class="col-sm-12">
            <div id="chartContainer" style="height: 370px; width: 100%;"></div>
        </div>

        <script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>

    </div>

<script>
window.onload = function () {

var chart = new CanvasJS.Chart("chartContainer", {
	animationEnabled: true,
    theme: "light1", // "light1", "light2", "dark1", "dark2"
	title: {
        text: "PF Wise Report Chart "
    },
    axisX: {
        interval: 1
    },
	axisY: {
		title: "Margin"
	},
	data: [{
		type: "column",
		dataPoints: @Html.Raw(ViewBag.DataPoints),
	}]
});
chart.render();

}
</script>

<script>

    $('#datepicker').datepicker({
        autoclose: true,
        format: 'dd-mm-yyyy'
    })

    $('#datepicker1').datepicker({
        autoclose: true,
        format: 'dd-mm-yyyy'
    })
</script>

@*<script>
    window.onload = function () {

    var chart = new CanvasJS.Chart("chartContainer", {
        animationEnabled: true,
        title: {
            text: "Women Nobel Laureates"
        },
        subtitles: [{
            text: "from 1903 to 2015"
        }],
        axisX: {
            title: "Axis X with interval 50",
            interval: 50
        },

        data: [{
            type: "bar",
            indexLabel: "{y}",
            dataPoints: @Html.Raw(ViewBag.DataPoints)
        }]
    });
    chart.render();

    }
    </script>*@

DtdcCashCounter/Views/Reports/ReceiptReports.cshtml
@model IEnumerable<DtdcCashCounter.Models.ReceiptDetailsModel>

@{
    ViewBag.Title = "ReceiptReports";
    Layout = "~/Views/Shared/CashCounterLayout.cshtml";

    string baseUrl = Request.Url.Scheme + "://" + Request.Url.Authority +
    Request.ApplicationPath.TrimEnd('/') + "/";
}

<link href="~/admin-lte/plugins/datatables/dataTables.bootstrap.css" rel="stylesheet" />
<link href="~/admin-lte/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css" rel="stylesheet" />
<script src="~/admin-lte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>



<div class="content-wrapper">
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header with-border">
                        <h3 class="box-title"> Receipt Report</h3>
                        @*<h3 class="box-title">Receipts Report</h3><h3 class="pull-right">Total Collection : ₹ @ViewBag.totalAmt </h3>*@
                    </div><!-- /.box-header -->
                    <div class="box-body">
                        @using (Html.BeginForm())
                        {
                            <div class="row">
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label>From Date:</label>
                                        <div class="input-group date">
                                            <div class="input-group-addon">
                                                <i class="fa fa-calendar"></i>
                                            </div>
                                            @if (ViewBag.Fromdatetime != null)
                                            {
                                                <input name="Fromdatetime" class="form-control pull-right" value="@ViewBag.Fromdatetime" id="datepicker" type="text">
                                            }
                                            else
                                            {
                                                <input name="Fromdatetime" class="form-control pull-right" id="datepicker" type="text">
                                            }
                                            @Html.ValidationMessage("Fromdateeror")
                                        </div>
                                    </div>

                                </div>


                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label>To Date:</label>

                                        <div class="input-group date">
                                            <div class="input-group-addon">
                                                <i class="fa fa-calendar"></i>
                                            </div>
                                            @if (ViewBag.ToDatetime != null)
                                            {
                                                <input name="ToDatetime" class="form-control pull-right" value="@ViewBag.ToDatetime" id="datepicker1" type="text">
                                            }
                                            else
                                            {
                                                <input name="ToDatetime" class="form-control pull-right" id="datepicker1" type="text">
                                            }
                                            @Html.ValidationMessage("Todateeror")
                                        </div>

                                    </div>
                                </div>

                                <div class="col-md-2">
                                    <div class="form-group">
                                        <label> </label>
                                        <button type="submit" id="sbmt" class="btn btn-block btn-primary sbmt">Search</button>
                                        <input type="submit" value="Export to Excel" name="Submit" class="btn btn-warning btn-block " />

                                    </div>
                                    <div class="col-sm-2">
                                    </div>
                                </div>

                            </div>
                        }

                        <table id="example1" class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>Sr.No</th>
                                    <th></th>
                                    <th>
                                        Consignment No
                                    </th>
                                    <th>
                                       Sender
                                    </th>
                                    <th>
                                        Sender Phone
                                    </th>
                                    <th>
                                       Reciepents Pincode
                                    </th>
                                    <th>
                                        Date
                                    </th>
                                    <th>
                                      Destination
                                    </th>
                                    <th>
                                       Actual Weight
                                    </th>
                                    <th>
                                        Volumetric Weight
                                    </th>
                                    
                                    <th>
                                        Total Amount
                                    </th>

                                </tr>
                            </thead>
                            <tbody>
                                @{ var i = 1;
                                    foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>
                                                @i
                                            </td>
                                            <td>
                                                <a href="@Url.Action("Download","Booking",new {id = item.Consignment_No })" target="_blank" class="btn btn-default">View</a>
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Consignment_No)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Sender)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.sender_phone)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.ReciepentsPincode)
                                            </td>
                                            <td>
                                                @item.Datetime_Cons.Value.ToString("dd/MM/yyyy")
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Destination)
                                            </td>

                                            <td>
                                                @Html.DisplayFor(modelItem => item.Actual_Weight)
                                            </td>


                                            <td>
                                                @Html.DisplayFor(modelItem => item.volumetric_Weight)
                                            </td>

                                            <td>
                                                @Html.DisplayFor(modelItem => item.Charges_Total)
                                            </td>

                                        </tr>
                                        i++;
                                    }

                                }

                            </tbody>

                        </table>
                        <br>
                        <!-- /input-group -->

                        <div class="col-sm-3 " style="float: right" ;>
                            <div class="input-group">
                                <div class="input-group-btn">
                                    <button type="button" class="btn btn-danger total-label">Total</button>
                                </div>
                                <!-- /btn-group -->
                                <input type="text" class="form-control" value="@Model.Sum(x=>x.Charges_Amount)">
                            </div>
                        </div>
                        <!-- /input-group -->
                    </div>
                </div>
            </div>
        </div>
    </section>

</div>


<script>

    $('#datepicker').datepicker({
        autoclose: true,
        format: 'dd-mm-yyyy'
    })

    $('#datepicker1').datepicker({
        autoclose: true,
        format: 'dd-mm-yyyy'
    })


</script>

<script>
    $(document).ready(function () {
        $('.sbmt').click(function () {
            var frmdate = $('#datepicker').val();

            var todate = $('#datepicker1').val();

            if (frmdate == "") {
                alert("Please Enter Start Date");
                return false;
            }
            else if (todate == "") {
                alert("Please Enter End Date");
                return false;
            }
            else {
                return true;
            }

        });

    });
</script>

<script type="text/javascript">
    $(function () {

        $('#example1').dataTable({
            "bPaginate": true,
            "bLengthChange": true,
            "bFilter": true,
            "bSort": true,
            "bInfo": true,
            "bAutoWidth": false
        });
    });
</script>

DtdcCashCounter/Views/Reports/WalletReports.cshtml
@model IEnumerable<DtdcCashCounter.EntityFr.WalletPoint>

@{
    ViewBag.Title = "WalletReports";
    Layout = "~/Views/Shared/CashCounterLayout.cshtml";
}


<div class="content-wrapper">
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header with-border">
                        <h3 class="box-title">Wallet Report</h3>
                    </div><!-- /.box-header -->
                    <div class="box-body">
                        <table id="example1" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>
                                        @Html.DisplayNameFor(model => model.MobileNo)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Wallet_Money)
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            <a href="@Url.Action("WalletHistory","Wallet",new {phone=item.MobileNo })">@item.MobileNo</a>
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Wallet_Money)
                        </td>

                    </tr>
}
                            </tbody>
                        </table>
                    </div>
                    </div>
                </div>
            </div>
                    </section>
    </div>

                    <script type="text/javascript">
                        $(function () {

                            $('#example1').dataTable({
                                "bPaginate": true,
                                "bLengthChange": true,
                                "bFilter": true,
                                "bSort": true,
                                "bInfo": true,
                                "bAutoWidth": false
                            });
                        });
                    </script>

DtdcCashCounter/Views/Reports/WalletReportsAdmin.cshtml
@model IEnumerable<DtdcCashCounter.EntityFr.WalletPoint>

@{
    ViewBag.Title = "WalletReports";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<link href="~/admin-lte/plugins/datatables/dataTables.bootstrap.css" rel="stylesheet" />

<div class="content-wrapper">
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box box-info">
                    <div class="box-header with-border">
                        <h3 class="box-title">Wallet Report</h3>
                    </div><!-- /.box-header -->
                    <div class="box-body">
                        @using (Html.BeginForm())
                        {
                            <div class="col-sm-2">
                                <input type="submit" value="Export to Excel" name="Submit" class="btn btn-block btn-success" />
                            </div>
                        }
                        <table id="example1" class="table table-striped table-bordered table-scroll table-responsive">
                            <thead>
                                <tr>

                                    <th>
                                        @Html.DisplayNameFor(model => model.Wallet_Money)
                                    </th>
                                    <th>
                                        Created date
                                    </th>
                                    <th>
                                        Name
                                    </th>
                                    <th>
                                        PF Code
                                    </th>
                                    <th>
                                        Redeemed
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.MobileNo)
                                    </th>

                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>

                                        <td>
                                            @Html.DisplayFor(modelItem => item.Wallet_Money)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Datetime_Wa)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Name)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.PFCode)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Redeemed)
                                        </td>

                                        <td>
                                            <a href="@Url.Action("WalletHistory","Wallet",new {phone=item.MobileNo })">@item.MobileNo</a>
                                        </td>


                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

<style>
    #example1 {
        display: block;
    }

    .table-scroll {
        height: 600px;
    }
</style>
<script type="text/javascript">
    $(function () {

        $('#example1').dataTable({
            "bPaginate": true,
            "bLengthChange": true,
            "bFilter": true,
            "bSort": true,
            "bInfo": true,
            "bAutoWidth": false
        });
    });
</script>